### ISSUE TITLE
Add information about how to save photos in custom directory

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/docs#136] opened 2022-03-22 14:12 UTC
For users it is hard to set up photo widget to store photos to custom folder. We should have a documentation how to do that. There are many obstacles:

See howto: https://lutraconsulting.slack.com/archives/CC95JK1T9/p1639493148382000

**Comment by PeterPetrik** [comment] 2022-03-24 12:42
duplicate of https://github.com/MerginMaps/docs/issues/65

**Closed by PeterPetrik** 2022-03-24 12:42 UTC
